catalogo:
    resource: 	"@CatalogoBundle/Resources/config/routing.yml"
    prefix:   	/
#Foi usado route como annotation na Action index   
catalogo:
    resource: 	"@CatalogoBundle/Controller"
    prefix:   	/
    type:		annotation	

hd_userbundle:
    resource: 	"@UserBundle/Controller"
    prefix:   	/
    type:		annotation	