# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # secures part of the application
        demo_secured_area:
            pattern:    ^/

            form_login:
                check_path: login_check
                login_path: login
                default_target_path: catalogo # Redirecionamento default depois de logado

            logout:
                path:   logout # Rota do lougout
                target: login # Depois de fazer lougout vai redirecionar
                
            anonymous: ~ # Permite Logar como anônimo
            #http_basic:
            #    realm: "Secured Demo Area"

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        # Para não ser necessário fazer isso para todas as rotas com segurana aqui
        # Faça no Controller
        - { path: ^/catalogo/new,       roles: ROLE_USER } # Para acessar essa route precisa ser ROLE_USER
        - { path: ^/catalogo/create,    roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }